server:
  port: 10012

spring:
  application:
    name: personDaily
  datasource:
    url: jdbc:mysql://119.29.187.18:3306/db_tfx?serverTimezone-UTC
    username: root
    password: tfx12138
    driver-class-name: com.mysql.cj.jdbc.Driver
#  rabbitmq:
#    host: 119.29.187.18
#    port: 15672
#    username: admin
#    password: admin
#    virtual-host: localhost
mybatis:
  mapper-locations: classpath:dao/*.xml

#邮件服务器
mail:
  user: t18370240624@163.com
  password: VQMXDDHSNABKUEEI
  host: smtp.163.com

