package com.tfxing.persondaily.entity.constant;

import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

@Component
public class JobOrderStateNodeConstant {

    private static final HashMap<String, List<String>> jobOrderStateRuleMap = new HashMap<>();
    @PostConstruct
    public void initMapData() {

        // 散杂货
        jobOrderStateRuleMap.put("LOT_BULK", Arrays.asList("PLACEORDER","CANCELSTOWAGE","BEPUTINSTORAGE","CLEARANCEOFGOODS","EXPORTCHECKINFORM",
                "EXPORTCHECK","EXPORTPERMITTHROUGH","OFFTHEHARBOUR","ARRIVALATPORT","IMPORTCHECKINFORM","IMPORTCHECK","IMPORTPERMITTHROUGH",
                "AFFIRMRECEIPT","INFORMSUPPFOOD","RECEIVESUPPFOOD","HBLMATCHANORDER","SENDBILL","SENDAORN","ACCOMPLISHCOPEWITH","ACCOMPLISHRECEIVABLE",
                "ACCOMPLISHMAKEINVOICE","GATHERINGACCOMPLISH","PAYMENTAPPLYFOR","PAYMENTACCOMPLISH",
                "HBLRELEASECARGO","MBLRELEASECARGO","HBLDETENTIONOFCARGO","MBLDETENTIONOFCARGO"));

        // 拼箱（自拼）
        jobOrderStateRuleMap.put("LOT_CONS", Arrays.asList("ACCOMPLISHCOPEWITH","ACCOMPLISHRECEIVABLE", "ACCOMPLISHMAKEINVOICE","GATHERINGACCOMPLISH",
                "PAYMENTAPPLYFOR","PAYMENTACCOMPLISH","HBLRELEASECARGO","MBLRELEASECARGO","HBLDETENTIONOFCARGO","MBLDETENTIONOFCARGO",
                "PLACEORDER","CANCELSTOWAGE","BEPUTINSTORAGE","BOOKINGSPACE","LETGOSPACE","SENDACAR","ENCASEMENT","RESTOREHEAVYBOX","CLEARANCEOFGOODS","SENDVGM",
                "SENDSHIPPINGBILL","EXPORTCHECKINFORM","EXPORTCHECK","EXPORTPERMITTHROUGH","OFFTHEHARBOUR","ARRIVALATPORT","IMPORTCHECKINFORM","IMPORTCHECK","IMPORTPERMITTHROUGH","RETURNEDEMPTYBOX",
                "AFFIRMRECEIPT","INFORMSUPPFOOD","RECEIVESUPPFOOD","HBLMATCHANORDER","MBLMATCHANORDER","SENDBILL","SENDAORN","MBLORIGINALMAIL"));

        // 拼箱（外拼）
        jobOrderStateRuleMap.put("LOT_LCL", Arrays.asList("ACCOMPLISHCOPEWITH","ACCOMPLISHRECEIVABLE", "ACCOMPLISHMAKEINVOICE","GATHERINGACCOMPLISH","PAYMENTAPPLYFOR","PAYMENTACCOMPLISH",
                "HBLRELEASECARGO","MBLRELEASECARGO","HBLDETENTIONOFCARGO","MBLDETENTIONOFCARGO",
                "PLACEORDER","CANCELSTOWAGE","BEPUTINSTORAGE","CLEARANCEOFGOODS","EXPORTCHECKINFORM","EXPORTCHECK","EXPORTPERMITTHROUGH","OFFTHEHARBOUR","ARRIVALATPORT","IMPORTCHECKINFORM","IMPORTCHECK","IMPORTPERMITTHROUGH"
                ,"AFFIRMRECEIPT","INFORMSUPPFOOD","RECEIVESUPPFOOD","HBLMATCHANORDER","SENDBILL","SENDAORN"));

        // 整箱
        jobOrderStateRuleMap.put("LOT_FCL", Arrays.asList("ACCOMPLISHCOPEWITH","ACCOMPLISHRECEIVABLE", "ACCOMPLISHMAKEINVOICE","GATHERINGACCOMPLISH","PAYMENTAPPLYFOR","PAYMENTACCOMPLISH",
                "HBLRELEASECARGO","MBLRELEASECARGO","HBLDETENTIONOFCARGO","MBLDETENTIONOFCARGO","DETAINRECEIPTS",
                "PLACEORDER","CANCELSTOWAGE","BOOKINGSPACE","LETGOSPACE","SENDACAR","ENCASEMENT","RESTOREHEAVYBOX","CLEARANCEOFGOODS","SENDVGM",
                "SENDSHIPPINGBILL","EXPORTCHECKINFORM","EXPORTCHECK","EXPORTPERMITTHROUGH","OFFTHEHARBOUR","ARRIVALATPORT","IMPORTCHECKINFORM","IMPORTCHECK","IMPORTPERMITTHROUGH","RETURNEDEMPTYBOX",
                "AFFIRMRECEIPT","INFORMSUPPFOOD","RECEIVESUPPFOOD","HBLMATCHANORDER","MBLMATCHANORDER","SENDBILL","SENDAORN","MBLORIGINALMAIL"));

        // 货主自拼
        jobOrderStateRuleMap.put("LOT_BUCO", Arrays.asList("ACCOMPLISHCOPEWITH","ACCOMPLISHRECEIVABLE", "ACCOMPLISHMAKEINVOICE","GATHERINGACCOMPLISH","PAYMENTAPPLYFOR","PAYMENTACCOMPLISH",
                "HBLRELEASECARGO","MBLRELEASECARGO","HBLDETENTIONOFCARGO","MBLDETENTIONOFCARGO","DETAINRECEIPTS",
                "PLACEORDER","CANCELSTOWAGE","BOOKINGSPACE","LETGOSPACE","SENDACAR","ENCASEMENT","RESTOREHEAVYBOX","CLEARANCEOFGOODS","SENDVGM",
                "SENDSHIPPINGBILL","EXPORTCHECKINFORM","EXPORTCHECK","EXPORTPERMITTHROUGH","OFFTHEHARBOUR","ARRIVALATPORT","IMPORTCHECKINFORM","IMPORTCHECK","IMPORTPERMITTHROUGH","RETURNEDEMPTYBOX",
                "AFFIRMRECEIPT","INFORMSUPPFOOD","RECEIVESUPPFOOD","HBLMATCHANORDER","MBLMATCHANORDER","SENDBILL","SENDAORN","MBLORIGINALMAIL"));
    }

    public static List<String> getJobOrderStateRuleMapByKey(String key) {
        return jobOrderStateRuleMap.get(key);
    }
}
